# TASK 3

# Part 1 - Single Layer Neural Network

In [15]:
# Defining inputs,weights and bias and calculation
inputs = [1.2, 5.2, 2.1]
weights = [3.1, 2.1, 8.1]
bias = 3
layer_output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias

In [16]:
print("Output Before Activation:", layer_output) 

Output Before Activation: 34.650000000000006


In [17]:
# My custom activation function
def custom_binary_activation(x):
    threshold = 50.0 
    return 1 if x > threshold else 0

In [22]:
custom_activation_ouput = custom_binary_activation(layer_output)
print("Custom Activation Function Output:", custom_activation_ouput)

Custom Activation Function Output: 0


In [23]:
# Applying the sigmoid activation function
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [24]:
output = sigmoid(layer_output)
print("Sigmoid Activation Function Output:", output)

Sigmoid Activation Function Output: 0.9999999999999991


# Part 2 - Single Layer Neural Network With Random Weights and Bias

In [26]:
# Defining the input values
inputs = [1.2, 5.2, 2.1]

In [53]:
# Generating random weights and bias
random_weights = np.random.rand(3)   
random_bias = np.random.randint(1, 101) 

In [54]:
print("Random Weights:", random_weights)
print("Random Bias:", random_bias)

Random Weights: [0.75378307 0.24678429 0.98437245]
Random Bias: 52


In [55]:
# Calculating the weighted sum of inputs and add bias
layer_output = np.dot(inputs, random_weights) + random_bias

In [56]:
print("Output Before Activation:", layer_output) 

Output Before Activation: 56.25500013829941


In [57]:
custom_activation_ouput = custom_binary_activation(layer_output)
print("Custom Activation Function Output:", custom_activation_ouput)

Custom Activation Function Output: 1


In [58]:
sigmoid_activation_output = sigmoid(layer_output)

In [59]:
print("Sigmoid Activation Function Output:", sigmoid_activation_output)

Sigmoid Activation Function Output: 1.0


# Part 3 - Multi Layer Neural Network With Multiple Neurons

### Input Layer With Multiple Neurons

In [61]:
# Defining the input values
inputs = np.array([1.2, 5.2, 2.1]) 

In [68]:
random_weights = np.random.rand(3, 3) # Change the shape (3, 3) as needed
random_biases = np.random.randint(1, 101, size=3)

In [69]:
print("Randomly Generated Weights:")
print(random_weights)
print("Randomly Generated Biases:", random_biases)

Randomly Generated Weights:
[[0.75540676 0.09981784 0.16583715]
 [0.95627156 0.58356671 0.23705143]
 [0.32029218 0.84086923 0.86238068]]
Randomly Generated Biases: [79 84  1]


In [70]:
# Calculating the weighted sums for each neuron
input_layer_output_without_activation = np.dot(inputs, random_weights) + random_biases

In [71]:
print("Input Layer Before Activation:", input_layer_output_without_activation) 

Input Layer Before Activation: [85.55171379 88.92015365  4.24267143]


In [74]:
def custom_binary_activation_multivalues(values):
    threshold = 50.0
    return np.where(values > threshold, 1, 0)

In [76]:
custom_activation_output = custom_binary_activation_multivalues(input_layer_output_without_activation)
print("Custom Activation Function Output:", custom_activation_output)

Custom Activation Function Output: [1 1 0]


In [98]:
input_layer_sigmoid_activation_output = sigmoid(input_layer_output_without_activation)

In [99]:
print("Sigmoid Activation Function Output For Input Layer:", input_layer_sigmoid_activation_output)

Sigmoid Activation Function Output For Input Layer: [1.         1.         0.98583439]


### Hidden Layer With Multiple Neurons

In [80]:
random_weights = np.random.rand(3, 3) # Change the shape (3, 3) as needed
random_biases = np.random.randint(1, 101, size=3)

In [81]:
print("Randomly Generated Weights:")
print(random_weights)
print("Randomly Generated Biases:", random_biases)

Randomly Generated Weights:
[[0.69008988 0.85615367 0.17134403]
 [0.56837014 0.03065268 0.88092611]
 [0.09014917 0.10189541 0.4258336 ]]
Randomly Generated Biases: [25  5 84]


In [100]:
# Calculating the weighted sums for each neuron
hidden_layer_output_without_activation = np.dot(input_layer_sigmoid_activation_output, random_weights) + random_biases

In [101]:
print("Hidden Layer Output Before Activation:", hidden_layer_output_without_activation) 

Hidden Layer Output Before Activation: [26.59240958  6.59240958 85.59240958]


In [102]:
custom_activation_output = custom_binary_activation_multivalues(hidden_layer_output_without_activation)
print("Custom Activation Function Output:", custom_activation_output)

Custom Activation Function Output: [0 0 1]


In [103]:
hidden_layer_sigmoid_activation_output = sigmoid(hidden_layer_output_without_activation)

In [104]:
print("Sigmoid Activation Function Output For Hidden Layer:", hidden_layer_sigmoid_activation_output)

Sigmoid Activation Function Output For Hidden Layer: [1.         0.99863114 1.        ]


### Output With Single Layer Neurons

In [105]:
# Generating random weights and bias
random_weights = np.random.rand(3)   
random_bias = np.random.randint(1, 101) 

In [106]:
print("Random Weights:", random_weights)
print("Random Bias:", random_bias)

Random Weights: [0.03108971 0.22688415 0.4645361 ]
Random Bias: 70


In [108]:
# Calculating the weighted sum of inputs and add bias
output_layer_before_activation = np.dot(hidden_layer_sigmoid_activation_output, random_weights) + random_bias

In [109]:
print("Output Layer Before Activation:", output_layer_before_activation)

Output Layer Before Activation: 70.72219939426297


In [116]:
custom_activation_ouput = custom_binary_activation(output_layer_before_activation)
print("Custom Activation Function Output:", custom_activation_ouput)

Custom Activation Function Output: 1


In [117]:
sigmoid_activation_output = sigmoid(output_layer_before_activation)

In [118]:
print("Final layer Output After Sigmoid Activation Function", sigmoid_activation_output)

Final layer Output After Sigmoid Activation Function 1.0
